# Generated by Django 5.2.13 on 2026-04-15 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('profile_summary', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=300, null=True)),
                ('github_portfolio_url', models.CharField(blank=True, max_length=300, null=True)),
                ('joining_date', models.CharField(blank=True, max_length=50, null=True)),
                ('manager_id', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('edu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('institution', models.CharField(blank=True, max_length=300, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('cgpa_or_percentage', models.FloatField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='records.employee')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('cert_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cert_name', models.CharField(max_length=300)),
                ('employee', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='records.employee')),
            ],
            options={
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('role_in_project', models.CharField(blank=True, max_length=200, null=True)),
                ('work_summary', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='records.employee')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='records.project')),
            ],
            options={
                'db_table': 'work',
            },
        ),
        migrations.CreateModel(
            name='WorkSkillAnalysis',
            fields=[
                ('analysis_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_analyses', to='records.skill')),
                ('work', models.ForeignKey(db_column='work_id', on_delete=django.db.models.deletion.CASCADE, related_name='skill_analyses', to='records.work')),
            ],
            options={
                'db_table': 'work_skill_analysis',
            },
        ),
        migrations.CreateModel(
            name='ProjectTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='records.project')),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='records.skill')),
            ],
            options={
                'db_table': 'project_tech',
                'unique_together': {('project', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_rating', models.FloatField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='records.employee')),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='records.skill')),
            ],
            options={
                'db_table': 'employee_skill',
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
