# Generated by Django 5.2.13 on 2026-04-15 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PreviousExperience',
            fields=[
                ('past_exp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=300, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, related_name='previous_experiences', to='records.employee')),
            ],
            options={
                'db_table': 'previous_experience',
            },
        ),
    ]
