# Generated by Django 5.2.13 on 2026-04-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.AddField(
            model_name='project',
            name='manager_id',
            field=models.CharField(blank=True, db_column='manager_id', max_length=200, null=True),
        ),
    ]
