# Generated by Django 5.2.13 on 2026-04-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_project_manager_project_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_utilization',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='utilization',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
