# Generated by Django 5.2.13 on 2026-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_employee_total_utilization_work_utilization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='IAM',
            field=models.CharField(choices=[('HR', 'HR'), ('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
    ]
